# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42716481a11f18f126ae96e599fef011005daee6f2fefb290ad701a0a52a333b40ec8ddf3fbdd34066968262a0513d8820f35c38cc65a470bdc50cc59ed17dc8

test:
  secret_key_base: 44cb41895323e1787b2e09d8cdcb6a193ee920878cb30c19dadbd2ce1adb84021d63f30724171147758e381aebaa3d77357c23bb791c2e0ced14ba59b57c38c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
